site_name: Convert - PowerShell Module for object conversions
repo_url: https://github.com/techthoughts2/rtdtest
site_author: Jake
edit_uri: edit/main/docs/
theme: readthedocs
copyright: "Convert is licensed under the <a href='https://github.com/austoonz/Convert/blob/master/LICENSE'>MIT license"
pages:
  - Home: index.md
  - Change Log: CHANGELOG.md
  - Functions:
    - Function1: functions/function1.md
